/// @description Insert description here
// You can write your code in this edito

//base hotkeys
global.buyHotkey = 87
global.upgradeHotkey = 88
global.abilityHotkey = 51
global.sellHotkey = 84
//other stuff

global.mode = "game";
global.tiermax = 5
global.countApm= false;
global.abilitycounter = 0;
global.abilityTime = 0;
global.comboStreak = 0;
global.combo = false;
global.comboTimer = 3*room_speed;


global._fhinputKeys[vk_escape] = "Esc";
global._fhinputKeys[vk_f1] = "F1";
global._fhinputKeys[vk_f2] = "F2";
global._fhinputKeys[vk_f3] = "F3";
global._fhinputKeys[vk_f4] = "F4";
global._fhinputKeys[vk_f5] = "F5";
global._fhinputKeys[vk_f6] = "F6";
global._fhinputKeys[vk_f7] = "F7";
global._fhinputKeys[vk_f8] = "F8";
global._fhinputKeys[vk_f9] = "F9";
global._fhinputKeys[vk_f10] = "F10";
global._fhinputKeys[vk_f11] = "F11";
global._fhinputKeys[vk_f12] = "F12";
global._fhinputKeys[145] = "SLok";
global._fhinputKeys[vk_pause] = "Pause";
global._fhinputKeys[192] = "~";
global._fhinputKeys[16] = "Shift";
global._fhinputKeys[18] = "Alt";
global._fhinputKeys[49] = "1";
global._fhinputKeys[50] = "2";
global._fhinputKeys[51] = "3";
global._fhinputKeys[52] = "4";
global._fhinputKeys[53] = "5";
global._fhinputKeys[54] = "6";
global._fhinputKeys[55] = "7";
global._fhinputKeys[56] = "8";
global._fhinputKeys[57] = "9";
global._fhinputKeys[48] = "0";
global._fhinputKeys[189] = "-";
global._fhinputKeys[187] = "=";
global._fhinputKeys[vk_backspace] = "BS";
global._fhinputKeys[65] = "A";
global._fhinputKeys[66] = "B";
global._fhinputKeys[67] = "C";
global._fhinputKeys[68] = "D";
global._fhinputKeys[69] = "E";
global._fhinputKeys[70] = "F";
global._fhinputKeys[71] = "G";
global._fhinputKeys[72] = "H";
global._fhinputKeys[73] = "I";
global._fhinputKeys[74] = "J";
global._fhinputKeys[75] = "K";
global._fhinputKeys[76] = "L";
global._fhinputKeys[77] = "M";
global._fhinputKeys[78] = "N";
global._fhinputKeys[79] = "O";
global._fhinputKeys[80] = "P";
global._fhinputKeys[81] = "Q";
global._fhinputKeys[82] = "R";
global._fhinputKeys[83] = "S";
global._fhinputKeys[84] = "T";
global._fhinputKeys[85] = "U";
global._fhinputKeys[86] = "V";
global._fhinputKeys[87] = "W";
global._fhinputKeys[88] = "X";
global._fhinputKeys[89] = "Y";
global._fhinputKeys[90] = "Z";
global._fhinputKeys[219] = "[";
global._fhinputKeys[221] = "]";
global._fhinputKeys[220] = "\\";
global._fhinputKeys[20] = "Caps";
global._fhinputKeys[186] = ";";
global._fhinputKeys[222] = "'";
global._fhinputKeys[13] = "Entr";
global._fhinputKeys[160] = "L Shift";
global._fhinputKeys[161] = "R Shift";
global._fhinputKeys[162] = "L Control";
global._fhinputKeys[163] = "R Control";
global._fhinputKeys[164] = "L Alt";
global._fhinputKeys[165] = "R Alt";
global._fhinputKeys[188] = ",";
global._fhinputKeys[190] = ".";
global._fhinputKeys[191] = "/";
global._fhinputKeys[vk_space] = "_";
global._fhinputKeys[93] = "App";
global._fhinputKeys[vk_insert] = "Ins";
global._fhinputKeys[vk_home] = "Hm";
global._fhinputKeys[vk_pageup] = "PgU";
global._fhinputKeys[vk_delete] = "Del";
global._fhinputKeys[vk_end] = "End";
global._fhinputKeys[vk_pagedown] = "PgD";
global._fhinputKeys[144] = "NL";
global._fhinputKeys[111] = "N/";
global._fhinputKeys[106] = "N*";
global._fhinputKeys[109] = "N-";
global._fhinputKeys[vk_numpad0] = "N0";
global._fhinputKeys[vk_numpad1] = "N1";
global._fhinputKeys[vk_numpad2] = "N2";
global._fhinputKeys[vk_numpad3] = "N3";
global._fhinputKeys[vk_numpad4] = "N4";
global._fhinputKeys[vk_numpad5] = "N5";
global._fhinputKeys[vk_numpad6] = "N6";
global._fhinputKeys[vk_numpad7] = "N7";
global._fhinputKeys[vk_numpad8] = "N8";
global._fhinputKeys[vk_numpad9] = "N9";
global._fhinputKeys[110] = "N.";
global._fhinputKeys[107] = "+";
global._fhinputKeys[vk_left] = "Left";
global._fhinputKeys[vk_right] = "Right";
global._fhinputKeys[vk_up] = "Up";
global._fhinputKeys[vk_down] = "Down";
global._fhinputKeys[9] = "Tab";